Bootstrap
IBUNHABIBU/Bootstrap-Project pull request #1
Opened 2019-08-05 14:50 UTC by IBUNHABIBU

2019-08-05 17:44 UTC, mosaaleb commented
Reviewing

2019-08-05 19:08 UTC, mosaaleb requested changes
### Hi @IBUNHABIBU  :wave:

Well done working on this project. The project looks very nice, but we have problems with page width on all media screens as it always show the horizontal scroll bar.


#### Mobile Screen:
- [ ] Let's fix this horizontal scroll bar
![out](https://user-images.githubusercontent.com/4246637/62487440-2099ce80-b7c2-11e9-9737-8c262b8d13c2.gif)

- [ ] The images should be responsive until it reaches the next breakpoint. 
![out](https://user-images.githubusercontent.com/4246637/62487667-b6cdf480-b7c2-11e9-8709-f794cfcc1681.gif)

- [ ] The more stories section should have the image on the left and text on the right section not stacked above each other.


#### Medium Screen:
![out1](https://user-images.githubusercontent.com/4246637/62514299-178b1a80-b81f-11e9-9550-449d2cde5163.gif)


- [ ] The same problem with horizontal scroll bar happens on medium screen
- [ ] The sections from Business to U.S. is not quite the same layout int the Newsweek page. We still need to apply the same layout.

#### Big Screen:
- [ ] Same with horizontal bar caused by the same element.

Please fix these issues and submit a new code review

### Happy Coding :computer:

2019-08-05 19:08 UTC, mosaaleb commented on index.html
> +    <link rel="stylesheet" href="Assets/CSS/app.css">
Since we have already referenced the bootstrap css files, we don't need all that files related to stylessheets bootstrap. Once you have `link`ed the bootstrap file, it will include the bootstrap files automatically

2019-08-06 09:43 UTC, IBUNHABIBU commented
Hi,
The horizontal scrollbar is the major problem for me every day I'm
struggling to get rid of this but I presume that , using position concept
may cause this problem but what approach other than position to position
items as you want.I need also some help from you
Regards
Ibunhabibu

Tarehe Jumatatu, Ago 5, 2019 saa 22:08 Muhammad <notifications@github.com>
aliandika:

> *@mosaaleb* requested changes on this pull request.
> Hi @IBUNHABIBU <https://github.com/IBUNHABIBU> 👋
>
> Well done working on this project. The project looks very nice, but we
> have problems with page width on all media screens as it always show the
> horizontal scroll bar.
> Mobile Screen:
>
>    -
>
>    Let's fix this horizontal scroll bar
>    [image: out]
>    <https://user-images.githubusercontent.com/4246637/62487440-2099ce80-b7c2-11e9-9737-8c262b8d13c2.gif>
>    -
>
>    The images should be responsive until it reaches the next breakpoint.
>    [image: out]
>    <https://user-images.githubusercontent.com/4246637/62487667-b6cdf480-b7c2-11e9-8709-f794cfcc1681.gif>
>    -
>
>    The more stories section should have the image on the left and text on
>    the right section not stacked above each other.
>
> Medium Screen:
>
>    - The same problem with horizontal scroll bar happens on medium screen
>    - The sections from Business to U.S. is not quite the same layout int
>    the Newsweek page. We still need to apply the same layout.
>
> Big Screen:
>
>    - Same with horizontal bar caused by the same element.
>
> Please fix these issues and submit a new code review
> Happy Coding 💻
> ------------------------------
>
> In index.html
> <https://github.com/IBUNHABIBU/Bootstrap-Project/pull/1#discussion_r310739479>
> :
>
> > @@ -0,0 +1,985 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +<head>
>
> +    <meta charset="UTF-8">
>
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0 ,shrink-to-fit=no">
>
> +
>
> +    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
>
> +    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
>
> +    <link rel="stylesheet" href="Assets/CSS/app.css">
>
>
> Since we have already referenced the bootstrap css files, we don't need
> all that files related to stylessheets bootstrap. Once you have linked
> the bootstrap file, it will include the bootstrap files automatically
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/IBUNHABIBU/Bootstrap-Project/pull/1?email_source=notifications&email_token=ADM4IS4XWWGHPQVO5WKU7TTQDB3DPA5CNFSM4IJMAT52YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCATDIOA#pullrequestreview-270939192>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADM4ISYQR6SFSOGZ3GN5DK3QDB3DPANCNFSM4IJMAT5Q>
> .
>

2019-08-06 10:21 UTC, mosaaleb commented
Hi @IBUNHABIBU,
The problem is mainly from relative positioning as you said, as it become harder to control on responsive screens. There are alternatives to position elements like flex or grid, even Bootstrap have classes for [flex](https://getbootstrap.com/docs/4.3/utilities/flex/) positioning. 

- Another problem from the `.new-letter2 h5` styles, which have width of 130%, it will surely outsize its container, if you removed this width the page will behave a much better on big screen.

- `padding: 1rem 50rem` in `slideshow-heading` is indication that you are doing something wrong `50rem` is very big padding which also will cause the width to increase significantly on medium screens.

As a rule of thumb bootstrap provide nearly all the positioning options for you, so you don't have to write any new classes other than changing the behavior of bootstrap defaults.

You can use tools to help you better inspect the page and figure out what is causing the page to behave not according to your expectations. One extension I love on chrome is [Pesticide](https://chrome.google.com/webstore/detail/pesticide-for-chrome/bblbgcheenepgnnajgfpiicnbbdmmooh). Also dev tools is your best friend in such cases, invest some time learning it and it will make your life easier. Contact me on slack (Muhammad Ebeid) if you still need help.

2019-08-06 10:33 UTC, IBUNHABIBU commented
Thank you Muhammad for your help
Let me work on it.


Tarehe Jumanne, Ago 6, 2019 saa 13:21 Muhammad <notifications@github.com>
aliandika:

> Hi @IBUNHABIBU <https://github.com/IBUNHABIBU>,
> The problem is mainly from relative positioning as you said, as it become
> harder to control on responsive screens. There are alternatives to position
> elements like flex or grid, even Bootstrap have classes for flex
> <https://getbootstrap.com/docs/4.3/utilities/flex/> positioning.
>
>    -
>
>    Another problem from the .new-letter2 h5 styles, which have width of
>    130%, it will surely outsize its container, if you removed this width the
>    page will behave a much better on big screen.
>    -
>
>    padding: 1rem 50rem in slideshow-heading is indication that you are
>    doing something wrong 50rem is very big padding which also will cause
>    the width to increase significantly on medium screens.
>
> As a rule of thumb bootstrap provide nearly all the positioning options
> for you, so you don't have to write any new classes other than changing the
> behavior of bootstrap defaults.
>
> You can use tools to help you better inspect the page and figure out what
> is causing the page to behave not according to your expectations. One
> extension I love on chrome is Pesticide
> <https://chrome.google.com/webstore/detail/pesticide-for-chrome/bblbgcheenepgnnajgfpiicnbbdmmooh>.
> Also dev tools is your best friend in such cases, invest some time learning
> it and it will make your life easier. Contact me on slack (Muhammad Ebeid)
> if you still need help.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/IBUNHABIBU/Bootstrap-Project/pull/1?email_source=notifications&email_token=ADM4IS7D4KPWNCRZD2JJW4LQDFGDDA5CNFSM4IJMAT52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3UVU5Y#issuecomment-518609527>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADM4IS3YPRQHCSMCPKG4E6TQDFGDDANCNFSM4IJMAT5Q>
> .
>

2019-08-07 19:01 UTC, samgaco commented
### @IBUNHABIBU :hand: 

### You have improved the website a lot since @mosaaleb review, but the horizontal scrolling bar seems to keep showing and there are some problems for the responsiveness in the medium size screen.

> ![skewed](https://user-images.githubusercontent.com/34820784/62650060-4952cd00-b956-11e9-910f-4b7691260b7e.png)

### If you could work on these things a bit more it would be good for the project to look polished and more professional. So far you are doing very well so keep the good work up :+1: 

**Please :pray: submit back for another code review when you commit these changes.**

2019-08-09 14:13 UTC, bolah2009 commented
Currently under review

2019-08-09 14:33 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-08-09 14:56 UTC, Torres-ssf commented
### Hi there @IBUNHABIBU 
You are working really hard on this project and should be proud of it :muscle: 
But it's no ready yet, we still need to make some changes on it:

We still need to work on the medium size from these sections. Try to make them match the same style from the original page.

![01](https://user-images.githubusercontent.com/30977845/62787724-b328bf00-ba9b-11e9-97cd-d6340ca05500.png)

Also, I notice that you are not using the linter. I know that in the past we didn't pay much attention to it but linting is important to reduce errors and improve the overall quality of your code. Using it also makes your project looks more professional. In the pathwrite, there are instructions on how to set up the linter. You will also need to fix the errors that it's going detect. Please kindly make the necessary changes and submit for code review again. Happy coding @IBUNHABIBU :+1:

2019-08-09 14:57 UTC, Torres-ssf requested changes
### Hi there @IBUNHABIBU 
You are working really hard on this project and should be proud of it :muscle: 
But it's no ready yet, we still need to make some changes on it:

We still need to work on the medium size from these sections. Try to make them match the same style from the original page.

![01](https://user-images.githubusercontent.com/30977845/62787724-b328bf00-ba9b-11e9-97cd-d6340ca05500.png)

Also, I notice that you are not using the linter. I know that in the past we didn't pay much attention to it but linting is important to reduce errors and improve the overall quality of your code. Using it also makes your project looks more professional. In the pathwrite, there are instructions on how to set up the linter. You will also need to fix the errors that it's going detect. Please kindly make the necessary changes and submit for code review again. Happy coding @IBUNHABIBU :+1:

2019-08-15 06:44 UTC, Oghenebrume50 commented
Reviewing.......

2019-08-15 06:56 UTC, Oghenebrume50 requested changes
Hi @IBUNHABIBU  Good Job on the progress so far, you have really learned a lot please add make try to make stickler work and fix errors detected, validate your HTML take care of all errors and warnings. While you are at it try to style the page better to make it come close to the original page especially on smaller screens, fix this and submit for re-review :pray:

2019-08-17 00:28 UTC, bolah2009 approved these changes
## Congratulations :clap: :medal_military: 

### Its a :+1: from me.

 Check out the comment below before merging.

- This project has nothing to do with most of the 195 files in this PR. Please, add unnecessary files to `.gitignore`

- Kindly, work more on making it look more like the source page. Some parts are missing padding/margin and some are not responsive.

Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-17 18:26 UTC, merged

2019-08-26 06:39 UTC, IBUNHABIBU commented
Hi,

I commented the below issue on github I need response

.main-para
{
text-align: center;
position: relative;
top: 20%;
left: 20%;
font-weight: bold;
opacity: 1;
font-size: 2.5rem;
width: 50%;
}
What's wrong with this block why there is so many errors caused by curled
bracket
e.g @stickler-ci <https://github.com/stickler-ci>
stickler-ci
/ stickler-ci

CSS/app.css#L126
Expected newline after "}" (block-closing-brace-newline-after) [error]
Unexpected whitespace at end of line (no-eol-whitespace) [error]

I tried so many times to adjust the indentation and curled bracket but the
errors are still present
any Idea?

Tarehe Jumamosi, Ago 17, 2019 saa 03:28 BOLA AHMED BUARI <
notifications@github.com> aliandika:

> *@bolah2009* approved this pull request.
> Congratulations 👏 🎖 Its a 👍 from me.
>
> Check out the comment below before merging.
>
>    -
>
>    This project has nothing to do with most of the 195 files in this PR.
>    Please, add unnecessary files to .gitignore
>    -
>
>    Kindly, work more on making it look more like the source page. Some
>    parts are missing padding/margin and some are not responsive.
>
> Good luck with your next project. 🌟
>
> Cheers
> Bola <https://bolabuari.com/>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/IBUNHABIBU/Bootstrap-Project/pull/1?email_source=notifications&email_token=ADM4IS5WNS5LEBBIKHJNYVDQE5A4NA5CNFSM4IJMAT52YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCB3KZXA#pullrequestreview-276212956>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADM4IS2QRNKWXC7I63XOV7DQE5A4NANCNFSM4IJMAT5Q>
> .
>